<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
            DB::table('users')->insert([
                    [
                    'user_login' => 'admin',
                    'user_email' => 'admin@golden-rivers.loc',
                    'user_hash_pass' => Hash::make('123456'),
                    'user_phone' => '9005996711',
                    'user_fullname' => 'Админов Админ Админович',
                    'user_sex' => true,
                    'role_id' => 1,
                    'user_status' => true,
                ],

                [
                    'user_login' => 'half_admin',
                    'user_email' => 'half_admin@golden-rivers.loc',
                    'user_hash_pass' => Hash::make('123456'),
                    'user_phone' => '9005996712',
                    'user_fullname' => 'Халфов Халв Халфович',
                    'user_sex' => true,
                    'role_id' => 2,
                    'user_status' => true,
                ],
                [
                    'user_login' => 'first_user',
                    'user_email' => 'first_user@golden-rivers.loc',
                    'user_hash_pass' => Hash::make('123456'),
                    'user_phone' => '9005996713',
                    'user_fullname' => 'Фестов Фест Вестович',
                    'user_sex' => true,
                    'role_id' => 2,
                    'user_status' => false,
                ],
                [
                    'user_login' => 'second_user',
                    'user_email' => 'second_user@golden-rivers.loc',
                    'user_hash_pass' => Hash::make('123456'),
                    'user_phone' => '9005996715',
                    'user_fullname' => 'Секондов Секнд Секондович',
                    'user_sex' => false,
                    'role_id' => 2,
                    'user_status' => false,
                ],
                [
                    'user_login' => 'againuser',
                    'user_email' => 'againuser@golden-rivers.loc',
                    'user_hash_pass' => Hash::make('123456'),
                    'user_phone' => '9005996714',
                    'user_fullname' => 'Эгейнов Эгейн Эйгенович',
                    'user_sex' => true,
                    'role_id' => 2,
                    'user_status' => true,
                ],
                    [
                        'user_login' => 'moreuser',
                        'user_email' => 'fmoreuser@golden-rivers.loc',
                        'user_hash_pass' => Hash::make('123456'),
                        'user_phone' => '9005996716',
                        'user_fullname' => 'Мов Мо Мооич',
                        'user_sex' => true,
                        'role_id' => 2,
                        'user_status' => false,
                    ],
                    [
                        'user_login' => 'flora13',
                        'user_email' => 'flora13@golden-rivers.loc',
                        'user_hash_pass' => Hash::make('123456'),
                        'user_phone' => '9005996717',
                        'user_fullname' => 'Флоров Влор Флорович',
                        'user_sex' => false,
                        'role_id' => 2,
                        'user_status' => true,
                    ],
                    [
                        'user_login' => 'dataman',
                        'user_email' => 'dataman@golden-rivers.loc',
                        'user_hash_pass' => Hash::make('123456'),
                        'user_phone' => '9005996718',
                        'user_fullname' => 'Дейтов Дейт Дейтович',
                        'user_sex' => false,
                        'role_id' => 2,
                        'user_status' => false,
                    ],
                    [
                        'user_login' => 'newman',
                        'user_email' => 'newman@golden-rivers.loc',
                        'user_hash_pass' => Hash::make('123456'),
                        'user_phone' => '9005996719',
                        'user_fullname' => 'Ньюманов Нью Ньюманович',
                        'user_sex' => true,
                        'role_id' => 2,
                        'user_status' => true,
                    ],
                    [
                        'user_login' => 'postman',
                        'user_email' => 'postman@golden-rivers.loc',
                        'user_hash_pass' => Hash::make('123456'),
                        'user_phone' => '9005996720',
                        'user_fullname' => 'Постманов Постман Постманович',
                        'user_sex' => true,
                        'role_id' => 2,
                        'user_status' => true,
                    ],
                    [
                        'user_login' => 'joyuser',
                        'user_email' => 'joyuser@golden-rivers.loc',
                        'user_hash_pass' => Hash::make('123456'),
                        'user_phone' => '9005996721',
                        'user_fullname' => 'Джоев Джой Джоивич',
                        'user_sex' => false,
                        'role_id' => 2,
                        'user_status' => false,
                    ],
                    [
                        'user_login' => 'dastiban',
                        'user_email' => 'dastiban@golden-rivers.loc',
                        'user_hash_pass' => Hash::make('123456'),
                        'user_phone' => '9005996722',
                        'user_fullname' => 'Дастибанов Дастин Дастинович',
                        'user_sex' => true,
                        'role_id' => 2,
                        'user_status' => false,
                    ],
                    [
                        'user_login' => 'beilish',
                        'user_email' => 'beilish@golden-rivers.loc',
                        'user_hash_pass' => Hash::make('123456'),
                        'user_phone' => '9005996723',
                        'user_fullname' => 'Белишов Беляш Беляшович',
                        'user_sex' => false,
                        'role_id' => 2,
                        'user_status' => true,
                    ],
                    [
                        'user_login' => 'lokk',
                        'user_email' => 'lokk@golden-rivers.loc',
                        'user_hash_pass' => Hash::make('123456'),
                        'user_phone' => '9005996724',
                        'user_fullname' => 'Локов Локи Локович',
                        'user_sex' => true,
                        'role_id' => 2,
                        'user_status' => false,
                    ],
                    [
                        'user_login' => 'herface',
                        'user_email' => 'herface@golden-rivers.loc',
                        'user_hash_pass' => Hash::make('123456'),
                        'user_phone' => '9005996725',
                        'user_fullname' => 'Хефесов Хефес Хефесович',
                        'user_sex' => true,
                        'role_id' => 2,
                        'user_status' => false,
                    ],
                    [
                        'user_login' => 'memto',
                        'user_email' => 'memto@golden-rivers.loc',
                        'user_hash_pass' => Hash::make('123456'),
                        'user_phone' => '9005996726',
                        'user_fullname' => 'Мемтоов Мемту Мемтуович',
                        'user_sex' => false,
                        'role_id' => 2,
                        'user_status' => true,
                    ],
                    [
                        'user_login' => 'storyyy',
                        'user_email' => 'storyyy@golden-rivers.loc',
                        'user_hash_pass' => Hash::make('123456'),
                        'user_phone' => '9005996727',
                        'user_fullname' => 'Сториев Стори Сториевич',
                        'user_sex' => true,
                        'role_id' => 2,
                        'user_status' => false,
                    ],
                    [
                        'user_login' => 'star11',
                        'user_email' => 'star11@golden-rivers.loc',
                        'user_hash_pass' => Hash::make('123456'),
                        'user_phone' => '9005996728',
                        'user_fullname' => 'Старов Стар Старович',
                        'user_sex' => true,
                        'role_id' => 2,
                        'user_status' => false,
                    ],
                    [
                        'user_login' => 'cre8tive',
                        'user_email' => 'cre8tive@golden-rivers.loc',
                        'user_hash_pass' => Hash::make('123456'),
                        'user_phone' => '9005996729',
                        'user_fullname' => 'Креативов Креатив Креативович',
                        'user_sex' => false,
                        'role_id' => 2,
                        'user_status' => true,
                    ],
                    [
                        'user_login' => 'login123',
                        'user_email' => 'login123@golden-rivers.loc',
                        'user_hash_pass' => Hash::make('123456'),
                        'user_phone' => '9005996730',
                        'user_fullname' => 'Логинов Логин Логинович',
                        'user_sex' => true,
                        'role_id' => 2,
                        'user_status' => false,
                    ],
                    [
                        'user_login' => 'qwerty',
                        'user_email' => 'qwerty@golden-rivers.loc',
                        'user_hash_pass' => Hash::make('123456'),
                        'user_phone' => '9005996731',
                        'user_fullname' => 'Квертов Кверти Квертович',
                        'user_sex' => true,
                        'role_id' => 2,
                        'user_status' => false,
                    ],
            ]
            );
    }
}
